Feature focus change
WayfireWM/wayfire-plugins-extra pull request #219
Opened 2023-12-15 02:26 UTC by Kim-Dewelski

This plugin allows the user to cycle through views using keybindings. This is similar to features seen in tiling window managers except it doesn't rely on tiling functionality.

The plugin provides a fair few options adjustable to the user so they can tweak it to their liking. The code hasn't successfully been tested on multiple outputs, and potentially the code related to the 'cross-output' settings isn't working properly.

2023-12-15 04:57 UTC, soreau requested changes
Looks good overall, although I haven't tested the code, I noticed a few things that need attention, and a few nitpicks.

2023-12-15 04:57 UTC, soreau commented on src/focus-change.cpp
> + * Copyright (c) 2023 Scott Moreau
You probably want to change this to your name.

2023-12-15 04:57 UTC, soreau commented on src/focus-change.cpp
> +    wf::option_wrapper_t<int32_t> grace_up{"focus-change/grace-up"},
You can just use `int` here..

2023-12-15 04:57 UTC, soreau commented on src/focus-change.cpp
> +    wf::option_wrapper_t<int32_t> scan_height{"focus-change/scan-height"},
.. and here.

2023-12-15 04:57 UTC, soreau commented on src/focus-change.cpp
> +    void rebind()
nitpick: I would probably drop the `re` prefix on this function name, since it's only called once.

2023-12-15 04:57 UTC, soreau commented on src/focus-change.cpp
> +    {}
You have to call `rem_binding()` for the bindings when you are finished with them, or else if you unload the plugin and use the keybinding, wayfire will likely crash.

2023-12-15 04:57 UTC, soreau commented on src/meson.build
> +focus_change = shared_module('focus-change', 'focus-change.cpp',
nitpick: Can we put this in alphabetical order?

2023-12-15 04:57 UTC, soreau commented on metadata/focus-change.xml
> +<?xml version="1.0"?>
You need to install this xml file by adding it in metadata/meson.build like the others.

2023-12-15 05:11 UTC, Kim-Dewelski commented
Aight I polished it a bit after your recommendations!

2023-12-15 05:17 UTC, soreau approved these changes

2023-12-17 03:48 UTC, Kim-Dewelski commented
fixed issue where working cross outputs did not function properly, but it should work now.

2023-12-17 05:01 UTC, soreau commented
The view that gains focus is not raised. Is this intentional, or would you like to make this functionality optional?

2023-12-17 06:03 UTC, merged